function [fitresult, gof, error] = createFit(timeThermal, temperature, error)
%CREATEFIT(TIMETHERMAL,TEMPERATURE)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : timeThermal
%      Y Output: temperature
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 10-Apr-2014 20:58:30


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( timeThermal, temperature, error);

% Set up fittype and options.
ft = fittype( '-20*b*exp(-x/(a))+310+c', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf -Inf];
opts.StartPoint = [0.959743958516081 0.340385726666133 0.585267750979777];
opts.Upper = [Inf Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( xData, fitresult);
hold on;
errorbar(xData, yData,error);

legend( h, 'temperature vs. timeThermal', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel( 'timeThermal' );
ylabel( 'temperature' );



